/* Autogenerated by png2wx.pl on Thu Feb 19 21:41:24 2009 */
#ifndef IMAGES_HPP
#define IMAGES_HPP 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_auto;
extern wxBitmap *_img_auto_over;
extern wxBitmap *_img_capture;
extern wxBitmap *_img_key;
extern wxBitmap *_img_key_on;
extern wxBitmap *_img_open;
extern wxBitmap *_img_open_over;
extern wxBitmap *_img_playmode;
extern wxBitmap *_img_rec;
extern wxBitmap *_img_rec_on;
extern wxBitmap *_img_recmode;
extern wxBitmap *_img_save;
extern wxBitmap *_img_save_over;
extern wxBitmap *_img_vu;
extern wxBitmap *_img_vu_full;

extern wxBitmap *_img_recoff;
extern wxBitmap *_img_recon;
#endif /* IMAGES_HPP */
